import { useEffect, useMemo, useState } from "react";
import { Search, SlidersHorizontal, Download, ReceiptText, WalletCards, CreditCard, FileText, Eye, CheckCircle2, MoreHorizontal, Plus, RefreshCw } from "lucide-react";
import { handleUnauthorized } from "../lib/auth";

type Debt = { id:number; guestName:string; phone:string|null; amount:number; paidAmount:number; remaining:number; status:"Open"|"Paid"; source:string; createdAt:string };
type Player = { id:number; name:string; username:string; debtBalance:number; walletBalance:number; image:string|null };
const money=(n:number)=>`${Number(n||0).toFixed(2)} DA`;

export default function GuestDebts(){
 const api=(window as any).api;
 const [debts,setDebts]=useState<Debt[]>([]); const [players,setPlayers]=useState<Player[]>([]);
 const [query,setQuery]=useState(""); const [tab,setTab]=useState<"All"|"Open"|"Paid">("All");
 const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [selected,setSelected]=useState<Debt|null>(null); const [quickMode,setQuickMode]=useState<"credit"|"payment"|null>(null); const [quickPlayer,setQuickPlayer]=useState(""); const [quickAmount,setQuickAmount]=useState("");
 async function load(){try{setLoading(true);setError("");const [guestRows,p]=await Promise.all([api.getGuestDebts({status:"All",limit:300}),api.getPlayers()]);const activePlayerDebts=(p as Player[]).filter(player=>Number(player.debtBalance||0)>0).map(player=>({id:-player.id,guestName:player.name,phone:player.username,amount:Number(player.debtBalance),paidAmount:0,remaining:Number(player.debtBalance),status:"Open" as const,source:"player debt",createdAt:new Date().toISOString()}));const playerPayments=(await Promise.all((p as Player[]).map(async player=>{try{const transactions=await api.getPlayerTransactions(player.id);return (transactions||[]).filter((tx:any)=>tx.type==="PLAYER_DEBT_PAYMENT").map((tx:any)=>({id:-1000000-Number(tx.id),guestName:player.name,phone:player.username,amount:Math.abs(Number(tx.amount||tx.debtChange||0)),paidAmount:Math.abs(Number(tx.amount||tx.debtChange||0)),remaining:0,status:"Paid" as const,source:"player payment",createdAt:tx.createdAt||new Date().toISOString()}))}catch{return []}}))).flat();setDebts([...(guestRows as Debt[]),...activePlayerDebts,...playerPayments]);setPlayers(p)}catch(e){console.error(e);setError("Could not load debt data")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const rows=useMemo(()=>debts.filter(d=>{const q=query.trim().toLowerCase();return (!q||d.guestName.toLowerCase().includes(q)||String(d.phone||"").includes(q))&&(tab==="All"||d.status===tab)}),[debts,query,tab]);
 const open=debts.filter(d=>d.status==="Open"); const paid=debts.filter(d=>d.status==="Paid");
 const outstanding=open.reduce((s,d)=>s+Number(d.remaining||0),0); const collected=debts.reduce((s,d)=>s+Number(d.paidAmount||0),0);
 const playerDebt=players.reduce((s,p)=>s+Math.max(0,Number(p.debtBalance||0)),0); const totalInvoices=debts.length;
 async function collect(d:Debt){if(!window.confirm(`Collect ${money(d.remaining)} from ${d.guestName}?`))return;try{if(d.source==="player debt"){await api.payPlayerDebt({playerId:Math.abs(d.id),amount:d.remaining,note:"Collected from Debt page"})}else{await api.settleGuestDebt({debtId:d.id,paidAmount:d.remaining,note:"Collected from Debt page"})}setSelected(null);await load()}catch(e){if(handleUnauthorized(e))return;setError("Could not collect debt")}} async function submitQuickAction(){const playerId=Number(quickPlayer),amount=Number(quickAmount);if(!playerId||!Number.isFinite(amount)||amount<=0){setError("Choose a player and valid amount");return}try{if(quickMode==="payment"){await api.payPlayerDebt({playerId,amount,note:"Collected from Debt page"})}else{await api.topUpPlayer({playerId,amount,note:"Credit from Debt page"})}setQuickMode(null);setQuickPlayer("");setQuickAmount("");await load()}catch(e){if(handleUnauthorized(e))return;setError(quickMode==="payment"?"Could not collect debt":"Could not add credit")}}
 const topPlayers=[...players].filter(p=>Number(p.debtBalance)>0).sort((a,b)=>Number(b.debtBalance)-Number(a.debtBalance)).slice(0,5);
 return <div dir="ltr" className="debt-reference space-y-3 text-white">
  <style>{`
   .debt-reference{font-size:12px}.debt-reference .panel{background:#202020;border:1px solid rgba(255,255,255,.09);border-radius:7px}.debt-reference .metric{min-height:78px;padding:12px}.debt-reference .metricIcon{width:42px;height:42px;border-radius:7px;display:grid;place-items:center}.debt-reference input{background:#1c1c1c}.debt-reference table{border-collapse:collapse}.debt-reference .row-paid{background:rgba(22,216,120,.055)}.debt-reference .row-open{background:rgba(216,6,39,.075)}.debt-reference th{font-size:10px;color:#aab1b9;font-weight:500}.debt-reference td{border-top:1px solid rgba(255,255,255,.06)}.debt-reference .smallBtn{height:29px;border-radius:5px;border:1px solid rgba(255,255,255,.1);background:#1c1c1c}.debt-reference .action{transition:.15s}.debt-reference .action:hover{filter:brightness(1.18)}
  `}</style>
  <section className="grid grid-cols-1 gap-3 xl:grid-cols-4">
   <Metric icon={<ReceiptText size={23}/>} iconClass="bg-rose-950 text-rose-400" title="Today Revenue" value={money(collected)} note="Collected payments" />
   <Metric icon={<WalletCards size={23}/>} iconClass="bg-violet-950 text-violet-400" title="This Week Revenue" value={money(collected)} note="Debt collection" />
   <Metric icon={<CreditCard size={23}/>} iconClass="bg-sky-950 text-sky-400" title="Unpaid Invoices" value={String(open.length)} note={money(outstanding)} warn />
   <Metric icon={<FileText size={23}/>} iconClass="bg-emerald-950 text-emerald-400" title="Total Invoices" value={String(totalInvoices)} note="All debt records" />
  </section>
  {error&&<div className="rounded-md border border-rose-500/30 bg-rose-950/30 px-3 py-2 text-rose-200">{error}</div>}
  <section className="grid gap-3 xl:grid-cols-[minmax(0,1fr)_330px]">
   <div className="space-y-3">
    <article className="panel overflow-hidden">
     <div className="flex flex-col gap-3 border-b border-white/10 p-3 lg:flex-row lg:items-center lg:justify-between"><div><h1 className="text-base font-semibold">Debts & Invoices</h1><p className="mt-1 text-white/45">Manage guest and player debt records</p></div><div className="flex gap-2"><label className="flex h-9 items-center gap-2 rounded-md border border-white/10 px-3"><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search invoices..." className="w-40 border-0 outline-none"/></label><button className="smallBtn px-3"><SlidersHorizontal size={13} className="inline mr-1"/>Filter</button><button className="smallBtn px-3"><Download size={13} className="inline mr-1"/>Export</button></div></div>
     <div className="flex gap-2 border-b border-white/10 px-3 py-2">{(["All","Paid","Open"] as const).map(t=><button key={t} onClick={()=>setTab(t)} className={`h-7 rounded px-3 text-[11px] ${tab===t?"bg-rose-700 text-white":"bg-white/[.04] text-white/70"}`}>{t==="All"?`All Invoices (${totalInvoices})`:t==="Paid"?`Paid (${paid.length})`:`Unpaid (${open.length})`}</button>)}</div>
     <div className="overflow-auto"><table className="w-full min-w-[720px] text-left"><thead><tr><th className="p-3">Invoice #</th><th>Customer</th><th>Type</th><th>Date</th><th>Amount</th><th>Status</th><th className="p-3">Actions</th></tr></thead><tbody>{rows.slice(0,12).map(d=><tr key={d.id} className={d.status==="Paid"?"row-paid":"row-open"}><td className="p-3 text-white/75">DEBT-{String(d.id).padStart(4,"0")}</td><td><b>{d.guestName}</b><p className="text-[10px] text-white/40">{d.phone||"Guest"}</p></td><td>{d.source}</td><td className="text-white/60">{new Date(d.createdAt).toLocaleDateString()}</td><td>{money(d.status==="Paid" ? d.amount : d.remaining)}</td><td><span className={d.status==="Paid"?"inline-flex rounded bg-emerald-500/15 px-2 py-1 text-emerald-300":"inline-flex rounded bg-rose-500/15 px-2 py-1 text-rose-300"}>● {d.status==="Paid"?"Paid":"Unpaid"}</span></td><td className="p-3"><div className="flex gap-1"><button onClick={()=>setSelected(d)} className="smallBtn w-7"><Eye size={14} className="mx-auto"/></button>{d.status==="Open"&&<button onClick={()=>void collect(d)} className="smallBtn w-7 text-emerald-400"><CheckCircle2 size={14} className="mx-auto"/></button>}<button className="smallBtn w-7"><MoreHorizontal size={14} className="mx-auto"/></button></div></td></tr>)}</tbody></table></div>
     <div className="flex items-center justify-between border-t border-white/10 p-3 text-white/45"><span>Showing {Math.min(rows.length,12)} of {rows.length} invoices</span><button onClick={()=>void load()} className="smallBtn px-3"><RefreshCw size={13} className={loading?"inline animate-spin":"inline"}/> Refresh</button></div>
    </article>
    <div className="grid gap-3 lg:grid-cols-2"><article className="panel p-3"><h2 className="font-semibold">Quick Actions</h2><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={()=>setQuickMode("payment")} className="action rounded-md bg-white/[.04] p-3 text-left"><ReceiptText className="mb-2 text-emerald-400" size={18}/><b className="block">Record Payment</b><span className="text-white/40">Collect unpaid debt</span></button><button onClick={()=>{setTab("Open");setQuery("")}} className="action rounded-md bg-white/[.04] p-3 text-left"><CreditCard className="mb-2 text-rose-400" size={18}/><b className="block">Unpaid Debts</b><span className="text-white/40">Review open items</span></button><button onClick={()=>setQuickMode("credit")} className="action rounded-md bg-white/[.04] p-3 text-left"><WalletCards className="mb-2 text-sky-400" size={18}/><b className="block">Add Credit</b><span className="text-white/40">Recharge player wallet</span></button><button onClick={()=>void load()} className="action rounded-md bg-white/[.04] p-3 text-left"><RefreshCw className="mb-2 text-violet-400" size={18}/><b className="block">Refresh Data</b><span className="text-white/40">Update balances</span></button></div></article><article className="panel p-3"><div className="flex items-center justify-between"><h2 className="font-semibold">Top Customers <span className="font-normal text-white/40">(Debt)</span></h2><button className="smallBtn px-2">View All</button></div><div className="mt-3 space-y-3">{topPlayers.map((p,i)=><div key={p.id} className="flex items-center justify-between"><span className="text-white/45">{i+1}</span><span className="flex-1 ml-3 truncate">{p.name}</span><b className="text-rose-300">{money(p.debtBalance)}</b></div>)}{!topPlayers.length&&<p className="text-white/40">No player debts</p>}</div></article></div>
   </div>
   <aside className="space-y-3"><article className="panel p-3"><div className="flex items-center justify-between"><h2 className="font-semibold">Debt Overview</h2><button className="smallBtn px-2">This Month</button></div><p className="mt-3 text-xl font-semibold">{money(outstanding)}</p><p className="mt-1 text-amber-400">● Open balance</p><div className="mt-5 h-24 rounded bg-gradient-to-t from-rose-950/70 to-transparent p-3 text-white/40">Debt trend overview</div></article><article className="panel p-3"><h2 className="font-semibold">Payment Methods</h2><div className="mt-4 flex items-center gap-5"><div className="grid h-28 w-28 place-items-center rounded-full border-[13px] border-rose-600"><b>{money(collected)}</b></div><div className="space-y-2"><p><i className="mr-2 inline-block h-2 w-2 rounded-full bg-rose-500"/>Collected {money(collected)}</p><p><i className="mr-2 inline-block h-2 w-2 rounded-full bg-amber-500"/>Outstanding {money(outstanding)}</p><p><i className="mr-2 inline-block h-2 w-2 rounded-full bg-violet-500"/>Player Debt {money(playerDebt)}</p></div></div></article><article className="panel p-3"><div className="flex items-center justify-between"><h2 className="font-semibold">Recent Invoices <span className="text-white/40">(Unpaid)</span></h2><button onClick={()=>setTab("Open")} className="smallBtn px-2">View All</button></div><div className="mt-3 space-y-3">{open.slice(0,5).map(d=><button onClick={()=>setSelected(d)} key={d.id} className="flex w-full justify-between text-left"><span><b className="block">DEBT-{String(d.id).padStart(4,"0")}</b><small className="text-white/45">{d.guestName}</small></span><span className="text-right"><b>{money(d.remaining)}</b><small className="block text-white/45">{new Date(d.createdAt).toLocaleDateString()}</small></span></button>)}</div><p className="mt-4 border-t border-white/10 pt-3 text-right font-semibold text-amber-400">Total Unpaid: {money(outstanding)}</p></article></aside>
  </section>
  {quickMode&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><form onSubmit={(e)=>{e.preventDefault();void submitQuickAction()}} className="panel w-full max-w-md p-5"><h2 className="text-lg font-semibold">{quickMode==="payment"?"Record Payment":"Add Credit"}</h2><p className="mt-2 text-white/45">{quickMode==="payment"?"Choose the player whose debt will be paid":"Choose player and recharge amount"}</p><select value={quickPlayer} onChange={e=>setQuickPlayer(e.target.value)} className="mt-4 h-11 w-full rounded-md border border-white/10 bg-[#1c1c1c] px-3"><option value="">Choose player</option>{players.filter(player=>quickMode==="credit"||Number(player.debtBalance)>0).map(player=><option key={player.id} value={player.id}>{player.name} (@{player.username}){quickMode==="payment"?` - Debt: ${money(player.debtBalance)}`:""}</option>)}</select><input value={quickAmount} onChange={e=>setQuickAmount(e.target.value)} placeholder="Amount" className="mt-3 h-11 w-full rounded-md border border-white/10 bg-[#1c1c1c] px-3"/><div className="mt-5 grid grid-cols-2 gap-3"><button type="button" onClick={()=>setQuickMode(null)} className="smallBtn">Cancel</button><button type="submit" className={quickMode==="payment"?"rounded-md bg-emerald-700":"rounded-md bg-sky-700"}>{quickMode==="payment"?"Collect Payment":"Add Credit"}</button></div></form></div>}
  {selected&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><div className="panel w-full max-w-md p-5"><h2 className="text-lg font-semibold">Debt Invoice</h2><p className="mt-3 text-white/60">{selected.guestName} · DEBT-{selected.id}</p><p className="mt-4 text-2xl font-semibold text-amber-400">{money(selected.remaining)}</p><div className="mt-5 grid grid-cols-2 gap-3"><button onClick={()=>setSelected(null)} className="smallBtn">Close</button>{selected.status==="Open"&&<button onClick={()=>void collect(selected)} className="rounded-md bg-emerald-600 text-sm">Collect payment</button>}</div></div></div>}
 </div>
}
function Metric({icon,iconClass,title,value,note,warn}:{icon:any;iconClass:string;title:string;value:string;note:string;warn?:boolean}){return <article className="panel metric"><div className="flex gap-3"><div className={`metricIcon ${iconClass}`}>{icon}</div><div><p className="text-white/65">{title}</p><p className="mt-1 text-lg font-semibold">{value}</p><p className={`mt-1 text-[11px] ${warn?"text-amber-400":"text-emerald-400"}`}>{note}</p></div></div></article>}
